// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abpmrijvfdeflxudhauy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFicG1yaWp2ZmRlZmx4dWRoYXV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxOTc2NjUsImV4cCI6MjA3MDc3MzY2NX0.1QVXzKcsOwPxfHbY1UXFyJEOp9u6Hv7tRT9ecJoXqbg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});