// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctiqhkzocrmbrdqqhmgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0aXFoa3pvY3JtYnJkcXFobWd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMzc3NTIsImV4cCI6MjA3MDkxMzc1Mn0.hkuPeBsaYUvmGS-NVF8Y8ql6R9rED0_pHgb5VcL0Q2U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});